// <auto-generated />
using System;
using AdsManagement.Modules.Report.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ReportContext))]
    [Migration("20241008124041_InitReportModule")]
    partial class InitReportModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdsManagement.Modules.Report.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReportId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedTime");

                    b.Property<int>("ReportObjectId")
                        .HasColumnType("int")
                        .HasColumnName("ReportObjectId");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReportType");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReporterId");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Solution");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("ReportId");

                    b.HasIndex("ReportObjectId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("AdsManagement.Modules.Report.Domain.Entities.ReportImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ImageId");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReportId");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Url");

                    b.HasKey("ImageId");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportImage", (string)null);
                });

            modelBuilder.Entity("AdsManagement.Modules.Report.Domain.Entities.ReportObject", b =>
                {
                    b.Property<int>("SurrogateKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurrogateKey"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DistrictName");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ObjectId");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ObjectType");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WardName");

                    b.HasKey("SurrogateKey");

                    b.HasIndex("ObjectId", "ObjectType")
                        .IsUnique();

                    b.ToTable("ReportObject", (string)null);
                });

            modelBuilder.Entity("AdsManagement.Modules.Report.Domain.Entities.Reporter", b =>
                {
                    b.Property<Guid>("ReporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReporterId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("ReporterId");

                    b.ToTable("Reporter", (string)null);
                });

            modelBuilder.Entity("AdsManagement.Modules.Report.Domain.Entities.Report", b =>
                {
                    b.HasOne("AdsManagement.Modules.Report.Domain.Entities.ReportObject", "ReportObject")
                        .WithMany("Reports")
                        .HasForeignKey("ReportObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdsManagement.Modules.Report.Domain.Entities.Reporter", "Reporter")
                        .WithMany("Reports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportObject");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("AdsManagement.Modules.Report.Domain.Entities.ReportImage", b =>
                {
                    b.HasOne("AdsManagement.Modules.Report.Domain.Entities.Report", "Report")
                        .WithMany("ReportImages")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("AdsManagement.Modules.Report.Domain.Entities.Report", b =>
                {
                    b.Navigation("ReportImages");
                });

            modelBuilder.Entity("AdsManagement.Modules.Report.Domain.Entities.ReportObject", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("AdsManagement.Modules.Report.Domain.Entities.Reporter", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
